[package]
name = "token_faucet"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
solana-program = "2.1.22"
spl-token = {version = "8.0.0", features = ["no-entrypoint"] }
